# Generated by Django 5.1 on 2024-08-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
